export const mainProducts = [
  {
    id: 1,
    name: "Honda GX200 Engine",
    price: 499.99,
    description:
      "A durable and reliable 196cc engine perfect for various applications.",
    category: "Motors",
    img: "https://example.com/img/honda-gx200.jpg",
  },
  {
    id: 2,
    name: "Briggs & Stratton 550EX",
    price: 399.99,
    description: "Compact and lightweight, ideal for smaller equipment.",
    category: "Motors",
    img: "https://example.com/img/briggs-550ex.jpg",
  },
  {
    id: 3,
    name: "Kawasaki FR691V",
    price: 999.99,
    description: "A powerful 726cc engine, great for commercial use.",
    category: "Motors",
    img: "https://example.com/img/kawasaki-fr691v.jpg",
  },
  {
    id: 4,
    name: "Yamaha MZ300",
    price: 649.99,
    description: "Rugged and reliable, designed for demanding tasks.",
    category: "Motors",
    img: "https://example.com/img/yamaha-mz300.jpg",
  },
  {
    id: 5,
    name: "Kohler Command Pro CH440",
    price: 749.99,
    description: "High-performing 14HP engine for heavy-duty applications.",
    category: "Motors",
    img: "https://example.com/img/kohler-ch440.jpg",
  },
  {
    id: 6,
    name: "Honda GX390",
    price: 999.99,
    description: "A large displacement 389cc engine with low emissions.",
    category: "Motors",
    img: "https://example.com/img/honda-gx390.jpg",
  },
  {
    id: 7,
    name: "Subaru EX17",
    price: 459.99,
    description: "Easy to start and lightweight with low noise levels.",
    category: "Motors",
    img: "https://example.com/img/subaru-ex17.jpg",
  },
  {
    id: 8,
    name: "Kohler SH265",
    price: 549.99,
    description: "A 6.5HP engine with superior fuel efficiency.",
    category: "Motors",
    img: "https://example.com/img/kohler-sh265.jpg",
  },
  {
    id: 9,
    name: "Robin Subaru EH72",
    price: 1199.99,
    description: "Heavy-duty performance with 25HP power output.",
    category: "Motors",
    img: "https://example.com/img/robin-subaru-eh72.jpg",
  },
  {
    id: 10,
    name: "Yanmar L100V",
    price: 899.99,
    description: "A small but mighty diesel engine for versatile uses.",
    category: "Motors",
    img: "https://example.com/img/yanmar-l100v.jpg",
  },
  {
    id: 11,
    name: "Generac G-Force 1000",
    price: 1299.99,
    description: "High-performance engine designed for generators.",
    category: "Motors",
    img: "https://example.com/img/generac-gforce1000.jpg",
  },
  {
    id: 12,
    name: "Briggs & Stratton 305cc",
    price: 799.99,
    description: "Medium-duty engine for various power equipment.",
    category: "Motors",
    img: "https://example.com/img/briggs-305cc.jpg",
  },
  {
    id: 13,
    name: "Honda iGX270",
    price: 1199.99,
    description: "An intelligent 270cc engine with electronic control.",
    category: "Motors",
    img: "https://example.com/img/honda-igx270.jpg",
  },
  {
    id: 14,
    name: "Lifan LF168F-2",
    price: 369.99,
    description: "Economical, versatile engine with low fuel consumption.",
    category: "Motors",
    img: "https://example.com/img/lifan-lf168f2.jpg",
  },
  {
    id: 15,
    name: "Kohler 3000 Series KT735",
    price: 849.99,
    description: "Pro-grade engine offering excellent durability.",
    category: "Motors",
    img: "https://example.com/img/kohler-kt735.jpg",
  },
  {
    id: 16,
    name: "Yamaha MX200",
    price: 549.99,
    description: "Quiet and fuel-efficient for medium-duty tasks.",
    category: "Motors",
    img: "https://example.com/img/yamaha-mx200.jpg",
  },
  {
    id: 17,
    name: "Briggs & Stratton Professional Series",
    price: 899.99,
    description: "Commercial-grade engine for professional landscapers.",
    category: "Motors",
    img: "https://example.com/img/briggs-professional-series.jpg",
  },
  {
    id: 18,
    name: "Kawasaki FX801V",
    price: 1299.99,
    description: "Top-tier engine offering outstanding power and performance.",
    category: "Motors",
    img: "https://example.com/img/kawasaki-fx801v.jpg",
  },
  {
    id: 19,
    name: "Honda GC190",
    price: 399.99,
    description:
      "A compact and easy-to-use engine for light-duty applications.",
    category: "Motors",
    img: "https://example.com/img/honda-gc190.jpg",
  },
  {
    id: 20,
    name: "Kohler Command Pro CV742",
    price: 1599.99,
    description: "A large commercial-grade engine for the toughest jobs.",
    category: "Motors",
    img: "https://example.com/img/kohler-cv742.jpg",
  },
  {
    id: 21,
    name: "Subaru EH65",
    price: 1249.99,
    description: "Heavy-duty engine perfect for commercial lawn equipment.",
    category: "Motors",
    img: "https://example.com/img/subaru-eh65.jpg",
  },
  {
    id: 22,
    name: "Yanmar TNV88",
    price: 2499.99,
    description: "A robust diesel engine for industrial equipment.",
    category: "Motors",
    img: "https://example.com/img/yanmar-tnv88.jpg",
  },
  {
    id: 23,
    name: "Honda GX630",
    price: 2099.99,
    description: "Premium V-twin engine for industrial applications.",
    category: "Motors",
    img: "https://example.com/img/honda-gx630.jpg",
  },
  {
    id: 24,
    name: "Briggs & Stratton Vanguard",
    price: 1999.99,
    description: "Designed for maximum durability and professional use.",
    category: "Motors",
    img: "https://example.com/img/briggs-vanguard.jpg",
  },
  {
    id: 25,
    name: "Kawasaki FS730V",
    price: 1499.99,
    description: "V-twin engine designed for reliable, high-performance use.",
    category: "Motors",
    img: "https://example.com/img/kawasaki-fs730v.jpg",
  },
  {
    id: 26,
    name: "Yanmar L70N",
    price: 749.99,
    description: "Diesel-powered engine offering exceptional fuel efficiency.",
    category: "Motors",
    img: "https://example.com/img/yanmar-l70n.jpg",
  },
  {
    id: 27,
    name: "Honda GX160",
    price: 449.99,
    description: "Versatile and reliable engine for small equipment.",
    category: "Motors",
    img: "https://example.com/img/honda-gx160.jpg",
  },
  {
    id: 28,
    name: "Kohler 7000 Series KT740",
    price: 1099.99,
    description: "Performance V-twin engine for zero-turn mowers.",
    category: "Motors",
    img: "https://example.com/img/kohler-kt740.jpg",
  },
  {
    id: 29,
    name: "Yamaha MZ360",
    price: 599.99,
    description: "Heavy-duty engine with high-torque output.",
    category: "Motors",
    img: "https://example.com/img/yamaha-mz360.jpg",
  },
  {
    id: 30,
    name: "Briggs & Stratton Intek",
    price: 499.99,
    description: "An affordable and durable engine for residential use.",
    category: "Motors",
    img: "https://example.com/img/briggs-intek.jpg",
  },
  {
    id: 31,
    name: "Subaru EH41",
    price: 1099.99,
    description: "A high-performance engine for outdoor power equipment.",
    category: "Motors",
    img: "https://example.com/img/subaru-eh41.jpg",
  },
  {
    id: 32,
    name: "Honda GX270",
    price: 649.99,
    description: "Perfect balance of power, economy, and reliability.",
    category: "Motors",
    img: "https://example.com/img/honda-gx270.jpg",
  },
  {
    id: 33,
    name: "Kawasaki FR651V",
    price: 1399.99,
    description: "Durable V-twin engine for light commercial use.",
    category: "Motors",
    img: "https://example.com/img/kawasaki-fr651v.jpg",
  },
  {
    id: 34,
    name: "Kohler Courage XT-7",
    price: 349.99,
    description: "Entry-level engine with efficient power output.",
    category: "Motors",
    img: "https://example.com/img/kohler-xt7.jpg",
  },
  {
    id: 35,
    name: "Yanmar 3TNM74",
    price: 2999.99,
    description: "A powerful three-cylinder diesel engine for tractors.",
    category: "Motors",
    img: "https://example.com/img/yanmar-3tnm74.jpg",
  },
  {
    id: 36,
    name: "Honda iGX440",
    price: 1699.99,
    description: "Advanced electronic control for optimized performance.",
    category: "Motors",
    img: "https://example.com/img/honda-igx440.jpg",
  },
  {
    id: 37,
    name: "Briggs & Stratton PowerBuilt",
    price: 599.99,
    description: "Reliable OHV engine for small lawn equipment.",
    category: "Motors",
    img: "https://example.com/img/briggs-powerbuilt.jpg",
  },
  {
    id: 38,
    name: "Kohler Command PRO EFI",
    price: 2199.99,
    description: "Fuel-efficient engine with electronic fuel injection.",
    category: "Motors",
    img: "https://example.com/img/kohler-pro-efi.jpg",
  },
  {
    id: 39,
    name: "Subaru EX21",
    price: 579.99,
    description: "Lightweight engine with excellent durability.",
    category: "Motors",
    img: "https://example.com/img/subaru-ex21.jpg",
  },
  {
    id: 40,
    name: "Honda GXV390",
    price: 899.99,
    description: "Vertical shaft engine for walk-behind mowers.",
    category: "Motors",
    img: "https://example.com/img/honda-gxv390.jpg",
  },
  {
    id: 41,
    name: "Kawasaki FS691V",
    price: 1349.99,
    description: "Perfect for zero-turn mowers with V-twin technology.",
    category: "Motors",
    img: "https://example.com/img/kawasaki-fs691v.jpg",
  },
  {
    id: 42,
    name: "Yanmar L48N",
    price: 649.99,
    description: "Compact diesel engine with excellent fuel efficiency.",
    category: "Motors",
    img: "https://example.com/img/yanmar-l48n.jpg",
  },
  {
    id: 43,
    name: "Briggs & Stratton OHV XR750",
    price: 499.99,
    description: "An efficient overhead valve engine for lawn mowers.",
    category: "Motors",
    img: "https://example.com/img/briggs-xr750.jpg",
  },
  {
    id: 44,
    name: "Subaru EX27",
    price: 749.99,
    description: "Durable engine with a smooth-running operation.",
    category: "Motors",
    img: "https://example.com/img/subaru-ex27.jpg",
  },
  {
    id: 45,
    name: "Honda GCV200",
    price: 429.99,
    description: "Lightweight, compact engine for small equipment.",
    category: "Motors",
    img: "https://example.com/img/honda-gcv200.jpg",
  },
  {
    id: 46,
    name: "Kawasaki FX921V",
    price: 2399.99,
    description: "Commercial-grade V-twin engine for high-end applications.",
    category: "Motors",
    img: "https://example.com/img/kawasaki-fx921v.jpg",
  },
  {
    id: 47,
    name: "Briggs & Stratton 1450 Series",
    price: 599.99,
    description: "Single-cylinder engine with a high-torque output.",
    category: "Motors",
    img: "https://example.com/img/briggs-1450.jpg",
  },
  {
    id: 48,
    name: "Subaru EX40",
    price: 949.99,
    description: "Efficient and durable with a large fuel tank capacity.",
    category: "Motors",
    img: "https://example.com/img/subaru-ex40.jpg",
  },
  {
    id: 49,
    name: "Kohler XT675",
    price: 349.99,
    description: "Affordable, lightweight engine for consumer applications.",
    category: "Motors",
    img: "https://example.com/img/kohler-xt675.jpg",
  },
  {
    id: 50,
    name: "Honda GX240",
    price: 749.99,
    description:
      "A versatile 270cc engine designed for performance and reliability.",
    category: "Motors",
    img: "https://example.com/img/honda-gx240.jpg",
  },
  {
    id: 51,
    name: "Car Floor Mats",
    price: 29.99,
    description: "Durable rubber floor mats to protect your car interior.",
    category: "Accessories",
    img: "https://example.com/img/car-floor-mats.jpg",
  },
  {
    id: 52,
    name: "Phone Mount",
    price: 19.99,
    description: "Hands-free phone mount for safe driving.",
    category: "Accessories",
    img: "https://example.com/img/phone-mount.jpg",
  },
  {
    id: 53,
    name: "Car Cover",
    price: 89.99,
    description: "Waterproof car cover for all-weather protection.",
    category: "Accessories",
    img: "https://example.com/img/car-cover.jpg",
  },
  {
    id: 54,
    name: "Steering Wheel Cover",
    price: 14.99,
    description: "Comfortable and stylish steering wheel cover.",
    category: "Accessories",
    img: "https://example.com/img/steering-wheel-cover.jpg",
  },
  {
    id: 55,
    name: "Car Air Freshener",
    price: 4.99,
    description: "Long-lasting car air freshener with fresh scents.",
    category: "Accessories",
    img: "https://example.com/img/car-air-freshener.jpg",
  },
  {
    id: 56,
    name: "Car Seat Organizer",
    price: 24.99,
    description: "Organizer with multiple pockets for backseat storage.",
    category: "Accessories",
    img: "https://example.com/img/car-seat-organizer.jpg",
  },
  {
    id: 57,
    name: "Blind Spot Mirror",
    price: 7.99,
    description: "Wide-angle blind spot mirror for safe lane changes.",
    category: "Accessories",
    img: "https://example.com/img/blind-spot-mirror.jpg",
  },
  {
    id: 58,
    name: "Trunk Organizer",
    price: 34.99,
    description: "Collapsible trunk organizer for versatile storage.",
    category: "Accessories",
    img: "https://example.com/img/trunk-organizer.jpg",
  },
  {
    id: 59,
    name: "USB Car Charger",
    price: 11.99,
    description: "Fast-charging dual-port USB charger for cars.",
    category: "Accessories",
    img: "https://example.com/img/usb-car-charger.jpg",
  },
  {
    id: 60,
    name: "Dash Cam",
    price: 129.99,
    description: "High-definition dash cam for recording your drives.",
    category: "Accessories",
    img: "https://example.com/img/dash-cam.jpg",
  },
  {
    id: 61,
    name: "Seat Cushion",
    price: 39.99,
    description: "Ergonomic seat cushion for extra comfort on long drives.",
    category: "Accessories",
    img: "https://example.com/img/seat-cushion.jpg",
  },
  {
    id: 62,
    name: "LED Headlights",
    price: 59.99,
    description:
      "Bright and energy-efficient LED headlights for improved visibility.",
    category: "Accessories",
    img: "https://example.com/img/led-headlights.jpg",
  },
  {
    id: 63,
    name: "Car Vacuum Cleaner",
    price: 49.99,
    description: "Portable vacuum cleaner for cleaning car interiors.",
    category: "Accessories",
    img: "https://example.com/img/car-vacuum.jpg",
  },
  {
    id: 64,
    name: "Sunshade",
    price: 14.99,
    description: "Foldable car sunshade to protect from heat and UV rays.",
    category: "Accessories",
    img: "https://example.com/img/sunshade.jpg",
  },
  {
    id: 65,
    name: "Jump Starter",
    price: 69.99,
    description: "Portable jump starter for emergencies on the road.",
    category: "Accessories",
    img: "https://example.com/img/jump-starter.jpg",
  },
  {
    id: 66,
    name: "Roof Rack",
    price: 199.99,
    description: "Universal roof rack for carrying extra cargo.",
    category: "Accessories",
    img: "https://example.com/img/roof-rack.jpg",
  },
  {
    id: 67,
    name: "Tire Pressure Gauge",
    price: 9.99,
    description: "Easy-to-read tire pressure gauge for optimal tire inflation.",
    category: "Accessories",
    img: "https://example.com/img/tire-pressure-gauge.jpg",
  },
  {
    id: 68,
    name: "Car Alarm System",
    price: 129.99,
    description: "Advanced car alarm system for added vehicle security.",
    category: "Accessories",
    img: "https://example.com/img/car-alarm-system.jpg",
  },
  {
    id: 69,
    name: "Car Battery Charger",
    price: 59.99,
    description:
      "Smart battery charger for maintaining and charging car batteries.",
    category: "Accessories",
    img: "https://example.com/img/car-battery-charger.jpg",
  },
  {
    id: 70,
    name: "Cargo Net",
    price: 24.99,
    description: "Durable cargo net to secure items in your trunk.",
    category: "Accessories",
    img: "https://example.com/img/cargo-net.jpg",
  },
  {
    id: 71,
    name: "Backup Camera",
    price: 89.99,
    description: "Wide-angle backup camera for safe parking and reversing.",
    category: "Accessories",
    img: "https://example.com/img/backup-camera.jpg",
  },
  {
    id: 72,
    name: "Headrest Pillow",
    price: 29.99,
    description: "Comfortable headrest pillow for neck support during drives.",
    category: "Accessories",
    img: "https://example.com/img/headrest-pillow.jpg",
  },
  {
    id: 73,
    name: "Hydraulic Jack",
    price: 79.99,
    description: "Compact hydraulic jack for easy tire changes.",
    category: "Accessories",
    img: "https://example.com/img/hydraulic-jack.jpg",
  },
  {
    id: 74,
    name: "Steering Wheel Lock",
    price: 39.99,
    description: "Heavy-duty steering wheel lock for added security.",
    category: "Accessories",
    img: "https://example.com/img/steering-wheel-lock.jpg",
  },
  {
    id: 75,
    name: "Windshield Wiper Blades",
    price: 19.99,
    description: "All-season windshield wiper blades for clear visibility.",
    category: "Accessories",
    img: "https://example.com/img/windshield-wipers.jpg",
  },
  {
    id: 76,
    name: "LED Interior Lights",
    price: 24.99,
    description: "Energy-efficient LED interior lights for a stylish look.",
    category: "Accessories",
    img: "https://example.com/img/led-interior-lights.jpg",
  },
  {
    id: 77,
    name: "Roof Cargo Box",
    price: 399.99,
    description: "Large roof cargo box for carrying extra luggage.",
    category: "Accessories",
    img: "https://example.com/img/roof-cargo-box.jpg",
  },
  {
    id: 78,
    name: "Car Dash Protector",
    price: 29.99,
    description: "Protect your dashboard from sun damage with this cover.",
    category: "Accessories",
    img: "https://example.com/img/dash-protector.jpg",
  },
  {
    id: 79,
    name: "Tire Inflator",
    price: 49.99,
    description: "Compact tire inflator for inflating tires on the go.",
    category: "Accessories",
    img: "https://example.com/img/tire-inflator.jpg",
  },
  {
    id: 80,
    name: "License Plate Frame",
    price: 12.99,
    description: "Stylish chrome license plate frame for a sleek look.",
    category: "Accessories",
    img: "https://example.com/img/license-plate-frame.jpg",
  },
  {
    id: 81,
    name: "Sun Visor Extender",
    price: 14.99,
    description: "Extend your sun visor for better glare protection.",
    category: "Accessories",
    img: "https://example.com/img/sun-visor-extender.jpg",
  },
  {
    id: 82,
    name: "Pet Seat Cover",
    price: 49.99,
    description:
      "Durable seat cover to protect your car seats from pet hair and dirt.",
    category: "Accessories",
    img: "https://example.com/img/pet-seat-cover.jpg",
  },
  {
    id: 83,
    name: "Car Window Shades",
    price: 9.99,
    description: "Set of window shades to block out sunlight.",
    category: "Accessories",
    img: "https://example.com/img/car-window-shades.jpg",
  },
  {
    id: 84,
    name: "Car Emergency Kit",
    price: 69.99,
    description: "Comprehensive car emergency kit for roadside assistance.",
    category: "Accessories",
    img: "https://example.com/img/car-emergency-kit.jpg",
  },
  {
    id: 85,
    name: "Car Seat Protector",
    price: 39.99,
    description: "Waterproof seat protector for cars with kids or pets.",
    category: "Accessories",
    img: "https://example.com/img/car-seat-protector.jpg",
  },
  {
    id: 86,
    name: "Keyless Entry System",
    price: 99.99,
    description: "Remote keyless entry system for easy access to your car.",
    category: "Accessories",
    img: "https://example.com/img/keyless-entry-system.jpg",
  },
  {
    id: 87,
    name: "Tire Chains",
    price: 119.99,
    description: "Durable tire chains for better traction in snow and ice.",
    category: "Accessories",
    img: "https://example.com/img/tire-chains.jpg",
  },
  {
    id: 88,
    name: "Car Seat Covers",
    price: 79.99,
    description:
      "Stylish and durable seat covers for added comfort and protection.",
    category: "Accessories",
    img: "https://example.com/img/car-seat-covers.jpg",
  },
  {
    id: 89,
    name: "Portable Car Refrigerator",
    price: 249.99,
    description:
      "Keep your drinks and food cool with this portable refrigerator.",
    category: "Accessories",
    img: "https://example.com/img/car-refrigerator.jpg",
  },
  {
    id: 90,
    name: "Car Wash Kit",
    price: 34.99,
    description: "Complete car wash kit with all essential cleaning tools.",
    category: "Accessories",
    img: "https://example.com/img/car-wash-kit.jpg",
  },
  {
    id: 91,
    name: "Heated Car Blanket",
    price: 59.99,
    description:
      "Electric heated blanket to keep you warm during winter drives.",
    category: "Accessories",
    img: "https://example.com/img/heated-car-blanket.jpg",
  },
  {
    id: 92,
    name: "Rear-View Mirror Dash Cam",
    price: 99.99,
    description: "Dual rear-view mirror and dash cam for better safety.",
    category: "Accessories",
    img: "https://example.com/img/rearview-mirror-dash-cam.jpg",
  },
  {
    id: 93,
    name: "Bluetooth Car Kit",
    price: 24.99,
    description: "Bluetooth car kit for hands-free calls and music streaming.",
    category: "Accessories",
    img: "https://example.com/img/bluetooth-car-kit.jpg",
  },
  {
    id: 94,
    name: "Windshield De-Icer",
    price: 9.99,
    description: "Spray-on de-icer to quickly remove ice from your windshield.",
    category: "Accessories",
    img: "https://example.com/img/windshield-deicer.jpg",
  },
  {
    id: 95,
    name: "Tire Shine Spray",
    price: 14.99,
    description: "Gives your tires a glossy, just-washed look.",
    category: "Accessories",
    img: "https://example.com/img/tire-shine-spray.jpg",
  },
  {
    id: 96,
    name: "Leather Conditioner",
    price: 19.99,
    description: "Conditions and protects leather seats from cracking.",
    category: "Accessories",
    img: "https://example.com/img/leather-conditioner.jpg",
  },
  {
    id: 97,
    name: "Towing Rope",
    price: 29.99,
    description: "Heavy-duty towing rope for pulling vehicles in emergencies.",
    category: "Accessories",
    img: "https://example.com/img/towing-rope.jpg",
  },
  {
    id: 98,
    name: "Roof Bike Rack",
    price: 149.99,
    description:
      "Easily transport your bikes with this secure roof-mounted rack.",
    category: "Accessories",
    img: "https://example.com/img/roof-bike-rack.jpg",
  },
  {
    id: 99,
    name: "Snow Scraper",
    price: 9.99,
    description: "Durable snow scraper for clearing ice and snow from windows.",
    category: "Accessories",
    img: "https://example.com/img/snow-scraper.jpg",
  },
  {
    id: 100,
    name: "Car Seat Gap Filler",
    price: 14.99,
    description: "Prevents items from falling between car seats.",
    category: "Accessories",
    img: "https://example.com/img/seat-gap-filler.jpg",
  },
];
